import "./globals.css";
import { Toaster } from "react-hot-toast";
import Providers from "./components/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} >
        <Providers>{children}</Providers>
        <Toaster/>
      </body>
    </html>
  );
}
